[package]
name = "integers-homework"
version = "0.1.0"
authors = ["Devron Baldwin <devron.baldwin@corestream.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
